---

- name: Chrome repo key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Chrome repository
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    update_cache: yes

- name: Install Chrome
  apt:
    name: google-chrome-stable
    state: latest
