---

##First Boot Configuration
- name: Hold Grub
  dpkg_selections:
    name: grub-common
    selection: hold

- name: Hold Grub2
  dpkg_selections:
    name: grub2-common
    selection: hold

- name: Install aptitude
  apt:
    pkg:
      - aptitude
    state: latest

- name: Update apt
  apt:
    update_cache: yes

- name: Install sudo
  apt:
    pkg:
      - sudo
    state: latest

- name: Create Alfred group
  group:
    name: alfred
    state: present
    gid: 1001

- name: Create Alfred user
  user:
    name: alfred
    shell: /bin/bash
    state: present
    uid: 1001
    group: alfred

- name: Add Alfred's authorized pub key
  authorized_key:
    user: alfred
    key: "https://raw.githubusercontent.com/ajcarberry/homelab/master/baseImages/ssh/alfred.pub"

- name: Allow sudo for Alfred
  copy:
    src: alfredadmin
    dest: /etc/sudoers.d/alfred
    owner: root
    group: root
    mode: 440

- name: Install common software
  apt:
    pkg:
      - build-essential
      - curl
      - dkms
      - dstat
      - dbus
      - "linux-headers-{{ ansible_kernel }}"
      - iftop
      - nfs-common
      - ntp
      - perl-base
      - python-pip
      - rsync
      - screen
      - tar
      - tcpdump
      - unzip
      - vim
    state: present

- name: Update OS
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
    force_apt_get: yes
    dpkg_options: 'force-confnew,force-confdef'
  register: "os_upgrade"

- name: Unconditionally reboot the machine with all defaults
  reboot:
  when: "os_upgrade.changed"
