---

##First Boot Configuration
- name: Hold Grub
  dpkg_selections:
    name:
      - grub-common
      - grub2-common
    selection: hold

- name: Install aptitude
  apt:
    pkg:
      - aptitude
    state: latest

- name: Update apt
  apt:
    update_cache: yes

- name: Install sudo
  apt:
    pkg:
      - sudo
    state: latest

- name: Create Alfred user
  user:
    name: alfred
    shell: /bin/bash
    state: present

- name: Add Alfred's authorized pub key
  authorized_key:
    user: alfred
    key: "https://raw.githubusercontent.com/ajcarberry/homelab/master/baseImages/ssh/alfred.pub"

- name: Allow sudo for Alfred
  copy:
    src: alfredadmin
    dest: /etc/sudoers.d/alfred
    owner: root
    group: root
    mode: 440

- name: Install common software
  apt:
    pkg:
      - "linux-headers-{{ ansible_kernel }}"
      - build-essential
      - perl-base
      - dkms
      - dstat
      - dbus
      - iftop
      - tcpdump
      - screen
      - curl
      - vim
      - rsync
      - ntp
      - python-pip
      - tar
      - unzip
    state: present

- name: Update OS
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
    force_apt_get: yes
    dpkg_options: 'force-confnew,force-confdef'
