---

- name: Aptly repo key
  apt_key:
    url: https://www.aptly.info/pubkey.txt
    state: present

- name: Aptly repository
  apt_repository:
    repo: "deb http://repo.aptly.info/ squeeze main"
    state: present
    update_cache: yes

- name: Un-hold Aptly
  dpkg_selections:
    name: aptly
    selection: install

- name: Install Aptly
  apt:
    name: "aptly={{ aptly_pkg_version }}"
    state: present

- name: Hold Aptly
  dpkg_selections:
    name: aptly
    selection: hold
