---

- name: Create Dev user
  user:
    name: "{{ dev_user }}"
    group: "sudo"
    password: "{{ dev_passwd }}"
    shell: /bin/bash
    state: present

- name: Configure Sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^%sudo'
    insertafter: '^%admin '
    line: '%sudo ALL=(ALL) NOPASSWD:ALL'

- name: Install Desktop GUI
  apt:
    pkg:
      - ubuntu-desktop
      - xrdp
    state: latest

- name: Make sure xrdp is running
  systemd:
    state: started
    enabled: yes
    name: xrdp

- name: Install various "other" tools for desktop environment
  apt:
    name:
      - terminator
    state: latest
