---

- name: Playbook to push all PVR configs
  hosts: all
  vars:
    efs_mount_stage: "fs-4a3d0200.efs.us-east-1.amazonaws.com:"
    efs_mount_prod: "fs-31afa27b.efs.us-east-1.amazonaws.com:"
    config_root: /mnt/EFS
    config_downloads: "{{ config_root }}/downloads"
    docker_sonarr_container_name: 'sonarr'
    docker_radarr_container_name: 'radarr'
    docker_nzbget_container_name: 'nzbget'
  remote_user: alfred
  become: yes
  roles:
    - common
    - docker
    - radarr
    - sonarr
    - nzbget
  tasks:
    - name: Create docker network
      docker_network:
        name: downloaders
        state: present
        connected:
          - "{{ docker_sonarr_container_name }}"
          - "{{ docker_radarr_container_name }}"
          - "{{ docker_nzbget_container_name }}"
