---

- name: Playbook to push plex config
  hosts: all
  vars:
    efs_mount_stage: "fs-4a3d0200.efs.us-east-1.amazonaws.com:"
    efs_mount_prod: "fs-31afa27b.efs.us-east-1.amazonaws.com:"
  remote_user: alfred
  become: yes
  roles:
    - common
    - docker
    - plex
    - tautulli
