---

- name: Playbook used to gracefully destroy Sonarr
  hosts: all
  remote_user: alfred
  become: yes
  vars:
    docker_sonarr_container_name: 'sonarr'
    docker_nzbget_container_name: 'nzbget'
  tasks:
  - name: Stop sonarr container
    docker_container:
      name: "{{ docker_sonarr_container_name }}"
      state: stopped
  - name: Run sonarr config backup script
    command: /home/sonarr/sonarr_backup.sh
  - name: Stop nzbget container
    docker_container:
      name: "{{ docker_nzbget_container_name }}"
      state: stopped
