---

env: stage

nzbget_user: nzbget
nzbget_group: nzbget
nzbget_id: 1206

config_root: /mnt/EFS
config_nzbget: "{{ config_root }}/nzbget"
config_downloads: "{{ config_root }}/downloads"

docker_nzbget_container_name: 'nzbget'
