---

packer_pkg_version: "1.2.5"
packer_arch: "amd64"
packer_path: /usr/local/bin
packer_url: "https://releases.hashicorp.com/packer/{{ packer_pkg_version }}/packer_{{ packer_pkg_version }}_linux_{{ packer_arch }}.zip"
