---

- name: Set EFS mount point to {{ efs_mount_stage }}
  set_fact:
    efs_mount: "{{ efs_mount_stage }}"
  when: env == "stage"

- name: Set EFS mount point to {{ efs_mount_prod }}
  set_fact:
    efs_mount: "{{ efs_mount_prod }}"
  when: env == "prod"

## Create tautulli user and group
- name: Create tautulli group
  group:
    name: "{{ tautulli_group }}"
    state: present
    gid: "{{ tautulli_id }}"

- name: Create tautulli user
  user:
    name: "{{ tautulli_user }}"
    shell: /bin/bash
    state: present
    uid: "{{ tautulli_id }}"
    group: "{{ tautulli_group }}"

- name: Create tautulli config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ tautulli_user }}"
    group: "{{ tautulli_group }}"
  with_items:
    - "{{ config_tautulli }}"
    - "{{ config_tautulli }}/config"

## Download, configure, and deploy Tautulli container
- name: Pull the tautulli docker image
  docker_image:
    name: "tautulli/tautulli"

- name: Start the tautulli docker container
  docker_container:
    image: "tautulli/tautulli"
    name: "{{ docker_tautulli_container_name }}"
    env:
      PUID: "{{ tautulli_id }}"
      PGID: "{{ tautulli_id }}"
      TZ: 'America/New_York'
    volumes:
      - '{{ config_tautulli }}/config:/config'
      - '{{ plex_logs }}:/plex_logs:ro'
    ports:
      - 8181:8181
    state: started
    restart_policy: always
